use projectcs3200;

INSERT INTO 
    department
    (short_name,
    long_name,
    college_id)
VALUES
    ("ARCH", "Architecture", 3),
    ("LARC", "Landscape Architecture", 3),
    ("ARTD", "Art - Media Arts", 3),
    ("ARTE", "Art - General", 3),
    ("ARTF", "Art - Fundamentals", 3),
    ("ARTG", "Art - Design", 3),
    ("ARTH", "Art - History", 3),
    ("ARTS", "Art - Studio", 3),
    ("GAME", "Game Design", 3),
    ("SMFA", "School of Museum of Fine Arts", 3),
    ("COMM", "Communication Studies", 3),
    ("JRNL", "Journalism", 3),
    ("MUSC", "Music", 3),
    ("MUSI", "Music Industry", 3),
    ("MUST", "Music Composition & Technology", 3),
    ("THTR", "Theatre", 3),
    ("SUEN", "MDES-SUEN", 3),
    ("AACE", "AACE", 3),
    ("ACCT", "Accounting", 9),
    ("BUSN", "Business Administration", 9),
    ("ENTR", "Entrepreneurship and Innovation", 9),
    ("FINA", "Finance and Insurance", 9),
    ("INTB", "International Business", 9),
    ("MGMT", "Management", 9),
    ("MISM", "Management Information Systems", 9),
    ("MGSC", "Management Science", 9),
    ("MKTG", "Marketing", 9),
    ("ORGB", "Organizational Behavior", 9),
    ("SCHM", "Supply Chain Management", 9),
    ("STRT", "Strategy", 9),
    ("CS", "Computer Science", 4),
    ("IS", "Information Science", 4),
    ("DS", "Data Science", 4),
    ("GSND", "Game Science and Design", 4),
    ("HINF", "Health Informatics", 4),
    ("IA", "Information Assurance and Cybersecurity", 4),
    ("CY", "Cybersecurity", 4),
    ("BIOE", "Bioengineering", 5),
    ("CHME", "Chemical Engineering", 5),
    ("CIVE", "Civil and Environmental Engineering", 5),
    ("SBSY", "Civil and Environmental Engineering", 5),
    ("EECE", "Electrical and Computer Engineering", 5),
    ("EMGT", "Engineering Management", 5),
    ("IE", "Industrial Engineering", 5),
    ("ME", "Mechanical Engineering", 5),
    ("ENLR", "Engineering Leadership", 5),
    ("CSYE", "Computer Systems Engineering", 5),
    ("ENSY", "Energy Systems", 5),
    ("INFO", "Information Systems", 5),
    ("TELE", "Telecommunication Systems", 5),
    ("MATL", "Materials Engineering", 5),
    ("MEIE", "Mechanical and Industrial Engineering", 5),
    ("SPLA", "Speech-Language Pathology and Audiology", 2),
    ("HSCI", "Health Science", 2),
    ("EXSC", "Cardiopulmonary and Exercise Sciences", 2),
    ("PHTH", "Public Health", 2),
    ("PT", "Physical Therapy", 2),
    ("PA", "Physician Assistant ", 2),
    ("NRSG", "Nursing", 2),
    ("PHMD", "Pharmacy Practice", 2),
    ("PHSC", "Pharmaceutical Science", 2),
    ("TOXC", "Toxicology", 2),
    ("BNSC", "Behavioral Neuroscience", 7),
    ("BIOC", "Biochemistry", 7),
    ("BIOL", "Biology", 7),
    ("BIOT", "Biotechnology", 7),
    ("CHEM", "Chemistry and Chemical Biology", 7),
    ("LING", "Linguistics", 7),
    ("MARS", "Marine Studies", 7),
    ("EEMB", "Ecology, Evolution, and Marine Biology", 7),
    ("ENVR", "Earth and Environmental Sciences", 7),
    ("ENVS", "Environmental Studies", 7),
    ("MATH", "Mathematics", 7),
    ("PHYS", "Physics", 7),
    ("PSYC", "Psychology", 7),
    ("ASNS", "Asian Studies", 8),
    ("CRIM", "Criminal Justice", 8),
    ("AFAM", "African-American", 8),
    ("AFRS", "African Studies", 8),
    ("AMSL", "American Sign Language", 8),
    ("ARAB", "Arabic", 8),
    ("CHNS", "Chinese", 8),
    ("FLNG", "Foreign Language", 8),
    ("FRNH", "French", 8),
    ("GRMN", "German", 8),
    ("GREK", "Greek", 8),
    ("HBRW", "Hebrew", 8),
    ("ITLN", "Italian", 8),
    ("JPNS", "Japanese", 8),
    ("CLTR", "Language, Literature, and Culture", 8),
    ("LANG", "Language, Literature, and Culture", 8),
    ("LITR", "Language, Literature, and Culture", 8),
    ("PORT", "Portuguese", 8),
    ("RSSN", "Russian", 8),
    ("SPNS", "Spanish", 8),
    ("SWHL", "Swahili", 8),
    ("ECON", "Economics", 8),
    ("ENGL", "English Language", 8),
    ("ENGW", "English Writing", 8),
    ("HIST", "History", 8),
    ("HUSV", "Human Services", 8),
    ("INTL", "International Affairs", 8),
    ("JWSS", "Jewish Studies", 8),
    ("PHIL", "Philosophy", 8),
    ("POLS", "Political Science", 8),
    ("ANTH", "Anthropology", 8),
    ("SOCL", "Sociology", 8),
    ("PPUA", "Public Policy and Urban Affairs", 8),
    ("LAW", "Law", 10);